[site]
title = "Zihao Wang"
description = "PhD Candidate at the Peking University."
favicon = "/favicon.svg"
last_updated = "November 28, 2025"

[author]
name = "Zihao Wang"
title = "PhD Student"
institution = "Peking University"
avatar = "/bio.jpg"

[social]
# Contact information (leave blank or delete to hide)

email = "zhwang@stu.pku.edu.cn"
location = "Beijing, China"
location_url = "https://maps.google.com"
location_details = [
  "5 Yiheyuan Rd, Haidian District",
  "Peking University, Beijing, China"
]
google_scholar = "https://scholar.google.com/citations?user=I0D-EgQAAAAJ"
github = "https://github.com/zhwang4ai"

[features]
# Show a like button on the about page
enable_likes = true

# Display all subpages on a single page
enable_one_page_mode = false

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"

[[navigation]]
title = "Teaching"
type = "page"
target = "teaching"
href = "/teaching"

[[navigation]]
title = "Awards"
type = "page"
target = "awards"
href = "/awards"

[[navigation]]
title = "Services"
type = "page"
target = "services"
href = "/services"

[[navigation]]
title = "CV"
type = "page"
target = "cv"
href = "/cv"
