name: Get Citation Data

on: 
  page_build: 
  schedule:
    - cron: '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write  # Ensure the bot has write permissions

    steps:
    - uses: actions/checkout@v2

    - name: Install Reqs
      run: |
        sudo apt-get install python3-setuptools

    - name: Run
      run: |
        cd ./google_scholar_crawler
        pip3 install -r requirements.txt
        python3 main.py
        cd ./results

        # Initialize git repository and set user config
        git init
        git config --local user.name "${GITHUB_ACTOR}"
        git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"

        # Set the remote repo URL using the secret token
        export remote_repo="https://${GITHUB_ACTOR}:${{ secrets.PAT_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"

        # Add and commit changes
        git add *.json
        git commit -m "Updated Citation Data"

        # Push changes to the remote repository
        git push "${remote_repo}" HEAD:google-scholar-stats --force

      env: 
        GOOGLE_SCHOLAR_ID: ${{ secrets.GOOGLE_SCHOLAR_ID }}
